pipeline{
    agent {
        node {
            label 'AGENT'
            
        }
}
    // environment { 
    //     GREETING = 'good morning'
    // }

    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
    }
    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

    //     booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }

    stages {
       
        stage ('init') {
            
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure

                """
            }
        }
        stage ('build') {
            steps {
                sh """
                    cd 01-vpc   
                    terraform plan 
                """
            }
        }
        stage ('deploye') {
            steps {
                 input {
                        message "Should we continue?"
                        ok "Yes, we should."
                //         submitter "Rajesh"
                //         parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
                sh """
                    cd 01-vpc 
                     terraform apply -auto-approve 
                """
            }
        }

        
    }
    post { 
        always { 
            echo 'I will always exicute run !'
        }
        failure { 
            echo 'I will always run when failure !'
        }
        success { 
            echo 'I will always run when success !'
        }
    }
}


