pipeline{
    agent {
        node {
            label 'AGENT'
            
        }
}
    // environment { 
    //     GREETING = 'good morning'
    // }

    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {

        choice(name: 'action', choices: ['apply', 'destroy', ], description: 'Pick something')

    }

    stages {
       
        stage ('init') {
            
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """
            }
        }
        stage ('plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan 
                """
            }
        }
        stage ('deploye') {
             when {
                expression {
                    ${params.action} == 'apply'
                }
            }
              input {
                    message "Should we continue?"
                    ok "Yes, we should."
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }

            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                
                """
            }
        }
        

        
    }

    // destroy

    stages {

        stage ('deploye') {
             when {
                expression {
                    ${params.action} == 'destroy'
                }
            }
              input {
                    message "Should we continue?"
                    ok "Yes, we should."
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }

            }
            steps {
                sh """
                    cd 01-vpc
                    terraform destroy -auto-approve
                
                """
            }
        }
        

        
    }
    post { 
        
        failure { 
            echo 'I will always run when failure !'
        }
        success { 
            echo 'I will always run when success !'
        }
    }
}
